import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class GameService {
  constructor() { }

  public cardBackLink:string = '/assets/images/cards/card_cover.png';
  public cardFrontLinks:{link: string}[] = [
    {link: '/assets/images/cards/ace_1.png'},
    {link: '/assets/images/cards/ace_2.png'},
    {link: '/assets/images/cards/ace_3.png'},
    {link: '/assets/images/cards/ace_4.png'},
    {link: '/assets/images/cards/ace_5.png'},
    {link: '/assets/images/cards/ace_6.png'},
    {link: '/assets/images/cards/ace_7.png'},
    {link: '/assets/images/cards/ace_8.png'},
    {link: '/assets/images/cards/ace_9.png'},
    {link: '/assets/images/cards/ace_10.png'},
    {link: '/assets/images/cards/ace_11.png'},
    {link: '/assets/images/cards/ace_12.png'},
    {link: '/assets/images/cards/ace_13.png'},
    {link: '/assets/images/cards/clubs_1.png'},
    {link: '/assets/images/cards/clubs_2.png'},
    {link: '/assets/images/cards/clubs_3.png'},
    {link: '/assets/images/cards/clubs_4.png'},
    {link: '/assets/images/cards/clubs_5.png'},
    {link: '/assets/images/cards/clubs_6.png'},
    {link: '/assets/images/cards/clubs_7.png'},
    {link: '/assets/images/cards/clubs_8.png'},
    {link: '/assets/images/cards/clubs_9.png'},
    {link: '/assets/images/cards/clubs_10.png'},
    {link: '/assets/images/cards/clubs_11.png'},
    {link: '/assets/images/cards/clubs_12.png'},
    {link: '/assets/images/cards/clubs_13.png'},
    {link: '/assets/images/cards/diamonds_1.png'},
    {link: '/assets/images/cards/diamonds_2.png'},
    {link: '/assets/images/cards/diamonds_3.png'},
    {link: '/assets/images/cards/diamonds_4.png'},
    {link: '/assets/images/cards/diamonds_5.png'},
    {link: '/assets/images/cards/diamonds_6.png'},
    {link: '/assets/images/cards/diamonds_7.png'},
    {link: '/assets/images/cards/diamonds_8.png'},
    {link: '/assets/images/cards/diamonds_9.png'},
    {link: '/assets/images/cards/diamonds_10.png'},
    {link: '/assets/images/cards/diamonds_11.png'},
    {link: '/assets/images/cards/diamonds_12.png'},
    {link: '/assets/images/cards/diamonds_13.png'},
    {link: '/assets/images/cards/hearts_1.png'},
    {link: '/assets/images/cards/hearts_2.png'},
    {link: '/assets/images/cards/hearts_3.png'},
    {link: '/assets/images/cards/hearts_4.png'},
    {link: '/assets/images/cards/hearts_5.png'},
    {link: '/assets/images/cards/hearts_6.png'},
    {link: '/assets/images/cards/hearts_7.png'},
    {link: '/assets/images/cards/hearts_8.png'},
    {link: '/assets/images/cards/hearts_9.png'},
    {link: '/assets/images/cards/hearts_10.png'},
    {link: '/assets/images/cards/hearts_11.png'},
    {link: '/assets/images/cards/hearts_12.png'},
    {link: '/assets/images/cards/hearts_13.png'},
    {link: '/assets/images/cards/ace_1.png'},
    {link: '/assets/images/cards/ace_1.png'},
    {link: '/assets/images/cards/ace_1.png'},
    {link: '/assets/images/cards/ace_1.png'},
    {link: '/assets/images/cards/ace_1.png'},
  ];
}
